### ISSUE TITLE
Question: Easy way to determine full_name of provided callable?

### ISSUE THREAD

**Issue by dmontagu** [sumerc/yappi#22] opened 2019-11-12 08:44 UTC
I'm wondering if there is a good way to convert a callable into its `full_name` representation, for passing to a filter. This would make it easier to extract targeted results from profiler output.

It seems to me this is, in general, the most reliable way to ensure you are getting the results of precisely the function you want to track, but I don't see an easy way to get the `full_name` of a function given just a reference to the function (it looks like this is computed inside the C code?). 

Perhaps I should just filter on the combination of `name` and `modname` instead?

**Comment by sumerc** [comment] 2019-11-12 10:03
Might be a good addition: the relevant code is in `code2pit`. The problem is I use frame object to format the name and thus you cannot simply call it from the Python side.
What you can do it you can use inspect module functions to mimic the same but using same code for both sides seems not possible at least currently. 
I also do not want to mess with code2pit implementation as it might break backward compat.(people generating diffs. for profiles) 
Having said that, I am open to an PR that tries best effort to mimic `code2pit` function. It is not that hard, but the code needs to be py2/3 compliant. So, if you want to give it a shot, I am ok, if not I am OK, too:)

**Comment by sumerc** [comment] 2019-12-17 21:27
Let's close this **question** for now as there is now easy way and the question is answered.

**Closed by sumerc** 2019-12-17 21:27 UTC
